


export type CountryData = {
  id: string;
  country: string;
  capital: string;
  tradeAgreement: string;
  tradeAgreementLink?: string;
  customsInfo: string;
  customsStrictness: string;
  logisticalInfo: string;
  detailsLink: string;
  fichaPaisLink: string;
  fichaPaisTooltip?: string;
  indicadoresLink: string;
  flagCode: string;
  language: string;
  currency: string;
  culture: string;
  topImports: string;
  countriesCrossed?: number;
  kilometers?: number;
};

export type ContinentsData = {
  [key: string]: CountryData[];
};

export const logisticData: ContinentsData = {
  'north-america': [
    { id: 'MEX', country: "México", capital: "Ciudad de México", tradeAgreement: "T-MEC", tradeAgreementLink: "https://www.gob.mx/t-mec", customsInfo: "https://www.gob.mx/anam", customsStrictness: "Alto, especialmente en sectores agroalimentario y farmacéutico.", logisticalInfo: "Negociación que valora las relaciones personales, pero también es directa. La jerarquía es importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.533772275888115,-82.83805222714534/Tec%C3%BAn-Um%C3%A1n,Guatemala/Mexico-City,MEX", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/mexico_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/mexico", flagCode: "mx", language: "Español", currency: "Peso Mexicano (MXN)", culture: "Cultura diversa y rica, con un fuerte sentido de identidad nacional y familia. La hospitalidad es clave.", topImports: "Maquinaria, vehículos, productos electrónicos, combustibles minerales.", countriesCrossed: 6, kilometers: 3286.36 },
    { id: 'USA', country: "Estados Unidos", capital: "Washington D.C.", tradeAgreement: "T-MEC", tradeAgreementLink: "https://www.gob.mx/t-mec", customsInfo: "https://www.cbp.gov/", customsStrictness: "Muy alto. Regulaciones estrictas en alimentos (FDA), productos electrónicos (FCC) y textiles.", logisticalInfo: "Negociación muy directa, rápida y enfocada en resultados y datos. La puntualidad es crucial.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.533772275888115,-82.83805222714534/Tec%C3%BAn-Um%C3%A1n,Guatemala/Mexico-City,MEX/Nuevo-Laredo/Texas", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/estadosunidos_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/estados-unidos", flagCode: "us", language: "Inglés", currency: "Dólar Estadounidense (USD)", culture: "Individualista y orientada a objetivos. La comunicación es directa y se valora la eficiencia.", topImports: "Vehículos, maquinaria, productos electrónicos, productos farmacéuticos.", countriesCrossed: 7, kilometers: 5015.69 },
    { id: 'CAN', country: "Canadá", capital: "Toronto", tradeAgreement: "T-MEC", tradeAgreementLink: "https://www.gob.mx/t-mec", customsInfo: "https://www.cbsa-asfc.gc.ca/", customsStrictness: "Alto, con requisitos bilingües (inglés/francés) para etiquetado en muchos productos.", logisticalInfo: "Negociación directa, pragmática y basada en hechos. Son cooperativos y buscan el beneficio mutuo.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.534085272307742,-82.83854695274897/Nicaragua,NIC/Laredo,TX,USA/Detroit,MI,USA/Toronto,ON,CAN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/canada_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/canada", flagCode: "ca", language: "Inglés, Francés", currency: "Dólar Canadiense (CAD)", culture: "Multicultural y reservada. Se valora la cortesía, la puntualidad y el respeto por el espacio personal.", topImports: "Vehículos, maquinaria, productos electrónicos, plásticos.", countriesCrossed: 8, kilometers: 7468.87 },
    { id: 'BLZ', country: "Belice", capital: "Belmopán", tradeAgreement: "CARICOM", tradeAgreementLink: "https://caricom.org/", customsInfo: "https://www.customs.gov.bz/", customsStrictness: "Bajo-Medio. Proceso generalmente ágil para bienes comunes.", logisticalInfo: "Negociación informal y directa. El inglés es el idioma oficial.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/Puntarenas,Corredores,Canoas,Paso-Canoas,CRI/Las-Manos,El-Para%C3%ADso,HND/Benque-Viejo-Del-Carmen-Town,BLZ/Belmopan,BLZ", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/belice_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/belice", flagCode: "bz", language: "Inglés", currency: "Dólar Beliceño (BZD)", culture: "Cultura relajada y amigable, con influencias caribeñas y mayas.", topImports: "Combustibles, maquinaria, alimentos procesados, tabaco.", countriesCrossed: 7, kilometers: 1474.98 },
    { id: 'CRI', country: "Costa Rica", capital: "San José", tradeAgreement: "Alianza del Pacífico (Miembro Asociado)", tradeAgreementLink: "https://alianzapacifico.net/", customsInfo: "https://www.hacienda.go.cr/aduanas/pasocanoas.html", customsStrictness: "Medio-Alto. Foco en regulaciones ambientales y sanitarias.", logisticalInfo: "Valoran la cortesía y la sostenibilidad. Estilo educado y menos directo.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/Carretera-Interamericana-Sur,Cartago,Dulce-Nombre,CRI/San-Jose,San-Jos%C3%A9,CRI", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/costa%20rica_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/costa-rica", flagCode: "cr", language: "Español", currency: "Colón Costarricense (CRC)", culture: "Conocida por su lema 'Pura Vida', la cultura es pacífica y valora la naturaleza y la educación.", topImports: "Combustibles, productos farmacéuticos, vehículos, maquinaria.", countriesCrossed: 2, kilometers: 801.58 },
    { id: 'SLV', country: "El Salvador", capital: "San Salvador", tradeAgreement: "SIECA", tradeAgreementLink: "https://www.sieca.int/", customsInfo: "https://sitio.aduana.gob.sv/", customsStrictness: "Alto en seguridad y control de mercancías ilícitas.", logisticalInfo: "Negociación directa y orientada a resultados. La seguridad es un tema importante.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.534085272307742,-82.83854695274897/Guasaule,El-Triunfo,Choluteca,HND/San-Salvador,SLV", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/elsalvador_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/el-salvador", flagCode: "sv", language: "Español", currency: "Dólar Estadounidense (USD)", culture: "Trabajadora y resiliente. La familia y la religión son pilares importantes.", topImports: "Textiles, combustibles, maquinaria, productos electrónicos.", countriesCrossed: 5, kilometers: 1641.88 },
    { id: 'GTM', country: "Guatemala", capital: "Ciudad de Guatemala", tradeAgreement: "SIECA", tradeAgreementLink: "https://www.sieca.int/", customsInfo: "https://portal.sat.gob.gt/portal/aduanas/", customsStrictness: "Variable. Puede haber retrasos y se requiere documentación precisa.", logisticalInfo: "Combinación de formalidad y relaciones personales. La jerarquía es respetada.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.534085272307742,-82.83854695274897/Guasaule,El-Triunfo,Choluteca,HND/Anguiat%C3%BA,Asunci%C3%B3n-Mita,Jutiapa,GTM", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/guatemala_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/guatemala", flagCode: "gt", language: "Español", currency: "Quetzal (GTQ)", culture: "Rica herencia maya. La familia es central y se valora el respeto a los mayores.", topImports: "Combustibles, maquinaria, vehículos, plásticos.", countriesCrossed: 6, kilometers: 1771.45 },
    { id: 'HND', country: "Honduras", capital: "Tegucigalpa", tradeAgreement: "SIECA", tradeAgreementLink: "https://www.sieca.int/", customsInfo: "https://www.aduanas.gob.hn/", customsStrictness: "Medio. Procesos en modernización, pero aún pueden ser complejos.", logisticalInfo: "Estilo de negociación relajado pero se valora el compromiso.", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.533772275888115,-82.83805222714534/Guasaule,El-Triunfo,Choluteca,HND/Tegucigalpa,HND", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/honduras_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/honduras", flagCode: "hn", language: "Español", currency: "Lempira (HNL)", culture: "Cálida y hospitalaria. La familia extendida y la comunidad son fundamentales.", topImports: "Textiles, combustibles, maquinaria, productos electrónicos.", countriesCrossed: 4, kilometers: 1507.42 },
    { id: 'NIC', country: "Nicaragua", capital: "Managua", tradeAgreement: "SIECA", tradeAgreementLink: "https://www.sieca.int/", customsInfo: "https://iml.com.ni/servicios-de-aduana/", customsStrictness: "Aduana Agua Caliente - Aduana El Amatillo", logisticalInfo: "Principales 10 productos que importan", detailsLink: "https://es.distance.to/Ciudad-de-Panam%C3%A1,Distrito-de-Panam%C3%A1,Panam%C3%A1,PAN/8.533772275888115,-82.83805222714534/Managua,", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nicaragua_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nicaragua", flagCode: "ni", language: "Español", currency: "Córdoba (NIO)", culture: "Gente amable y orgullosa de su herencia poética y revolucionaria.", topImports: "Maquinaria, combustibles, vehículos, productos farmacéuticos.", countriesCrossed: 3, kilometers: 2704.92 },
  ],
  'south-america': [
    { id: 'ARG', country: 'Argentina', capital: 'Buenos Aires', tradeAgreement: 'MERCOSUR', tradeAgreementLink: "https://www.mercosur.int/", customsInfo: 'https://www.argentina.gob.ar/arca/aduana', customsStrictness: "Alto. Restricciones cambiarias y licencias no automáticas afectan la importación.", logisticalInfo: "Formal en apertura, buscan vínculo personal; les gusta debatir con intensidad.", detailsLink: "https://es.distance.to/Lima,PER/Paso-De-Jama,Coranzuli,Susques,Jujuy,ARG/Buenos-Aires,Ciudad-Aut%C3%B3noma-de-Buenos-Aires,ARG", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argentina_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argentina", flagCode: "ar", language: "Español", currency: "Peso Argentino (ARS)", culture: "Fuerte influencia europea. Se valora la socialización, la pasión por el fútbol y la buena comida.", topImports: "Maquinaria, vehículos, productos químicos, soja.", countriesCrossed: 4, kilometers: 4008.49 },
    { id: 'BOL', country: "Bolivia", capital: "La Paz", tradeAgreement: "MERCOSUR", tradeAgreementLink: "https://www.mercosur.int/", customsInfo: "https://www.aduana.gob.bo/", customsStrictness: "Medio-Alto. Procesos burocráticos pueden ser lentos. Sensible en sector agrícola.", logisticalInfo: "Negociación formal, protocolar, orientada a la jerarquía.", detailsLink: "https://es.distance.to/Lima,PER/La-Paz,BOL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/bolivia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/bolivia", flagCode: "bo", language: "Español, Quechua, Aymara", currency: "Boliviano (BOB)", culture: "Plurinacional, con fuerte presencia de culturas indígenas. La familia y la comunidad son centrales.", topImports: "Combustibles, vehículos, maquinaria, productos de acero.", countriesCrossed: 2, kilometers: 1521.12 },
    { id: 'BRA', country: "Brasil", capital: "Brasilia", tradeAgreement: "MERCOSUR", tradeAgreementLink: "https://www.mercosur.int/", customsInfo: "http://www.receita.fazenda.gov.br/", customsStrictness: "Muy alto. Burocracia compleja y sistema tributario denso.", logisticalInfo: "Relacional y entusiasta. La paciencia es clave, las decisiones pueden tomar tiempo.", detailsLink: "https://es.distance.to/Lima,PER/Puerto-Maldonado,Tambopata,Madre-de-Dios,PER/-10.94148674006737,-69.57706868075934/Bras%C3%ADlia,Distrito-Federal,BRA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/brasil_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/brasil", flagCode: "br", language: "Portugués", currency: "Real Brasileño (BRL)", culture: "Vibrante y diversa. El carnaval, el fútbol y la música (samba, bossa nova) son mundialmente famosos.", topImports: "Maquinaria, productos electrónicos, vehículos, combustibles.", countriesCrossed: 2, kilometers: 5281.9 },
    { id: 'CHL', country: "Chile", capital: "Santiago", tradeAgreement: "Alianza del Pacífico", tradeAgreementLink: "https://alianzapacifico.net/", customsInfo: "https://www.aduana.cl/", customsStrictness: "Alto. Muy eficientes y regulados, especialmente en productos agrícolas (SAG).", logisticalInfo: "Directa, profesional y formal. Valoran la eficiencia y la preparación.", detailsLink: "https://es.distance.to/Lima,PER/Santiago,Metropolitana-de-Santiago,CHL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/chile_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/chile", flagCode: "cl", language: "Español", currency: "Peso Chileno (CLP)", culture: "Más reservada y formal que otros países de la región. Valoran la estabilidad y el orden.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 2, kilometers: 3326.84 },
    { id: 'COL', country: "Colombia", capital: "Bogota", tradeAgreement: "Alianza del Pacífico", tradeAgreementLink: "https://alianzapacifico.net/", customsInfo: "https://www.dian.gov.co/", customsStrictness: "Alto. Controles estrictos en café, flores y esmeraldas.", logisticalInfo: "Negociación formal pero amigable. Se valora la relación personal.", detailsLink: "https://es.distance.to/Lima,PER/Ibarra,ECU/Bogot%C3%A1,Distrito-Capital,COL", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/colombia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/colombia", flagCode: "co", language: "Español", currency: "Peso Colombiano (COP)", culture: "Alegre y diversa. La música (cumbia, vallenato) y el café son parte de su identidad.", topImports: "Maquinaria, productos electrónicos, vehículos, productos químicos.", countriesCrossed: 3, kilometers: 2884.44 },
    { id: 'ECU', country: "Ecuador", capital: "Quito", tradeAgreement: "Miembro Asociado MERCOSUR", tradeAgreementLink: "https://www.mercosur.int/documento/decision-n-59-04-acuerdo-de-complementacion-economica-mercosur-comunidad-andina-colombia-ecuador-y-venezuela/", customsInfo: "https://www.aduana.gob.ec/", customsStrictness: "Medio-Alto. Regulaciones estrictas para importación de alimentos y vehículos.", logisticalInfo: "Negociación formal y respetuosa. La puntualidad es importante.", detailsLink: "https://es.distance.to/Lima,PER/Quito,ECU", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/ecuador_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/ecuador", flagCode: "ec", language: "Español", currency: "Dólar Estadounidense (USD)", culture: "Megadiverso cultural y geográficamente (Andes, Costa, Amazonía, Galápagos).", topImports: "Combustibles, maquinaria, productos químicos, vehículos.", countriesCrossed: 2, kilometers: 1782.75 },
    { id: 'PRY', country: "Paraguay", capital: "Asunción", tradeAgreement: "MERCOSUR", tradeAgreementLink: "https://www.mercosur.int/", customsInfo: "https://www.aduana.gov.py/", customsStrictness: "Medio. Especialmente en la frontera con Brasil y Argentina por contrabando.", logisticalInfo: "Formal pero flexible; se valora la relación personal.", detailsLink: "https://es.distance.to/Lima,PER/Tambo-Quemado,Turco,BOL/Sucre,BOL/-20.563225454395017,-62.26633958829666/-20.63535463961231,-62.01986971151268/Asunci%C3%B3n,Distrito-Capital,PRY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/paraguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/paraguay", flagCode: "py", language: "Español, Guaraní", currency: "Guaraní (PYG)", culture: "Bilingüe y hospitalaria. El 'tereré' es una costumbre social importante.", topImports: "Productos electrónicos, vehículos, maquinaria, tabaco.", countriesCrossed: 4, kilometers: 3477.62 },
    { id: 'URY', country: "Uruguay", capital: "Montevideo", tradeAgreement: "MERCOSUR", tradeAgreementLink: "https://www.mercosur.int/", customsInfo: "https://www.aduanas.gub.uy/", customsStrictness: "Medio. Considerada una de las aduanas más eficientes de la región.", logisticalInfo: "Formal, sobrio y pragmático; ser claro y confiable.", detailsLink: "https://es.distance.to/Lima,PER/Montevideo,URY", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uruguay_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uruguay", flagCode: "uy", language: "Español", currency: "Peso Uruguayo (UYU)", culture: "Similar a la argentina, con gran afición por el mate y el asado. Estable y secular.", topImports: "Petróleo crudo, vehículos, productos químicos, maquinaria.", countriesCrossed: 5, kilometers: 4243.43 },
    { id: 'VEN', country: "Venezuela", capital: "Caracas", tradeAgreement: "TLC PERU - VENEZUELA", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-por-entrar-en-vigencia/venezuela", customsInfo: "http://declaraciones.seniat.gob.ve/", customsStrictness: "Muy alto y complejo debido a la situación política y económica.", logisticalInfo: "Relacional, centrada en la confianza; la puntualidad es flexible.", detailsLink: "https://es.distance.to/Lima,PER/Caracas,Libertador,Distrito-Capital,VEN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/venezuela_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/venezuela", flagCode: "ve", language: "Español", currency: "Bolívar Digital (VED)", culture: "Alegre y extrovertida. La música, como el joropo, y la familia son muy importantes.", topImports: "Alimentos, productos farmacéuticos, maquinaria, productos químicos.", countriesCrossed: 4, kilometers: 4302.19 },
  ],
  'europe': [
    { id: 'ALB', country: "Albania", capital: "Tirana", tradeAgreement: "Negociaciones con UE", tradeAgreementLink: "https://www.consilium.europa.eu/es/press/press-releases/2025/09/16/eu-opens-accession-negotiations-with-albania-on-green-and-sustainable-connectivity-policies/", customsInfo: "https://www.dogana.gov.al/", customsStrictness: "Medio. En proceso de alineación con estándares de la UE.", logisticalInfo: "La negociación puede ser lenta, se valora la relación personal.", detailsLink: "https://maps.app.goo.gl/BL91W9DqTM5yPvSU6", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ALBANIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/AL", flagCode: "al", language: "Albanés", currency: "Lek (ALL)", culture: "Hospitalaria y basada en códigos de honor tradicionales. La familia es fundamental.", topImports: "Maquinaria, alimentos, textiles, productos químicos.", countriesCrossed: 8 },
    { id: 'DEU', country: "Alemania", capital: "Berlín", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/germany_es", customsInfo: "https://www.zoll.de/DE/Home/home_node.html", customsStrictness: "Muy Alto. Famosos por su eficiencia y estricto cumplimiento de las normativas de la UE.", logisticalInfo: "Directa, formal y muy estructurada. Los datos y hechos son cruciales.", detailsLink: "https://maps.app.goo.gl/NpDKrCGTudiLJFrSA", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ALEMANIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/DE", flagCode: "de", language: "Alemán", currency: "Euro (EUR)", culture: "Organizada, puntual y eficiente. La separación entre la vida privada y profesional es marcada.", topImports: "Vehículos, maquinaria, productos químicos, productos electrónicos.", countriesCrossed: 2 },
    { id: 'AUT', country: "Austria", capital: "Viena", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/austria_es", customsInfo: "https://www.bmf.gv.at/services/aemter-behoerden/zaoe.html", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Formal, bien preparada y enfocada en la calidad.", detailsLink: "https://maps.app.goo.gl/C35Y2mdP8kCy82ju5", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/AUSTRIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/AT", flagCode: "at", language: "Alemán", currency: "Euro (EUR)", culture: "Formal, conservadora y amante de la música y las artes.", topImports: "Maquinaria, vehículos, productos farmacéuticos, productos electrónicos.", countriesCrossed: 4 },
    { id: 'BEL', country: "Bélgica", capital: "Bruselas", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/belgium_es", customsInfo: "https://finances.belgium.be/fr/douanes_accises", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Pragmática y multilingüe. La negociación puede ser en inglés, francés u holandés.", detailsLink: "https://maps.app.goo.gl/CLwiJwJgJ73zFgSY9", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/BELGICA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/BE", flagCode: "be", language: "Neerlandés, Francés, Alemán", currency: "Euro (EUR)", culture: "Dividida culturalmente entre Flandes y Valonia. Aprecian la modestia y el trabajo duro.", topImports: "Productos químicos, maquinaria, vehículos, productos farmacéuticos.", countriesCrossed: 2 },
    { id: 'BGR', country: "Bulgaria", capital: "Sofia", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/bulgaria_es", customsInfo: "https://customs.bg/wps/portal/agency/home", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Relacional y hospitalaria, pero puede ser burocrática.", detailsLink: "https://maps.app.goo.gl/78B1MaUJQ77py5mN8", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/BULGARIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/BG", flagCode: "bg", language: "Búlgaro", currency: "Lev (BGN)", culture: "Orgullosa de su herencia eslava y tradiciones folclóricas.", topImports: "Maquinaria, combustibles, metales, textiles.", countriesCrossed: 7 },
    { id: 'CZE', country: "Chequia", capital: "Praga", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/czechia_es", customsInfo: "https://celnisprava.gov.cz/cz/o-nas/Stranky/celni-sprava.aspx", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Directa, algo formal y enfocada en los detalles técnicos.", detailsLink: "https://maps.app.goo.gl/JfSh93ABPXNEVzVp6", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/CHECAREPUBLICA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/CZ", flagCode: "cz", language: "Checo", currency: "Corona Checa (CZK)", culture: "Reservada pero amigable. Gran aprecio por la historia y la cerveza.", topImports: "Maquinaria, vehículos, productos electrónicos, metales.", countriesCrossed: 3 },
    { id: 'HRV', country: "Croacia", capital: "Zagreb", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/croatia_es", customsInfo: "https://carina.gov.hr/pristup-informacijama/propisi-i-sporazumi/carinsko-postupanje/2726", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Relacional y directa. El turismo es un sector clave.", detailsLink: "https://maps.app.goo.gl/Yijca93tNe9Q3tCz7", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/CROACIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/HR", flagCode: "hr", language: "Croata", currency: "Euro (EUR)", culture: "Cultura mediterránea y centroeuropea. Fuertemente orientada a la familia y las tradiciones.", topImports: "Combustibles, maquinaria, vehículos, productos farmacéuticos.", countriesCrossed: 6 },
    { id: 'DNK', country: "Dinamarca", capital: "Copenhague", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/denmark_es", customsInfo: "https://sktst.dk/english", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Directa, informal y basada en el consenso. El diseño y la sostenibilidad son importantes.", detailsLink: "https://maps.app.goo.gl/YPn8pMPVPUUSqDfP7", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/DINAMARCA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/DK", flagCode: "dk", language: "Danés", currency: "Corona Danesa (DKK)", culture: "Igualitaria, valora el 'hygge' (acogedor). La confianza y la honestidad son fundamentales.", topImports: "Maquinaria, vehículos, productos farmacéuticos, productos electrónicos.", countriesCrossed: 2 },
    { id: 'SVK', country: "Eslovaquia", capital: "Bratislava", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/slovakia_es", customsInfo: "https://www.mfsr.sk/sk/dane-cla-uctovnictvo/colna-oblast/", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Formal y orientada a los detalles. La preparación es clave.", detailsLink: "https://maps.app.goo.gl/sMshwfroMoynF2y46", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ESLOVAQUIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/SK", flagCode: "sk", language: "Eslovaco", currency: "Euro (EUR)", culture: "Hospitalaria y tradicional. Fuerte apego a la naturaleza y el folclore.", topImports: "Vehículos, maquinaria, productos electrónicos, combustibles.", countriesCrossed: 5 },
    { id: 'SVN', country: "Eslovenia", capital: "Liubliana", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/slovenia_es", customsInfo: "https://www.fu.gov.si/carina/poslovanje_z_nami/e_carina", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Eficiente, directa y bien preparada. Valoran la puntualidad.", detailsLink: "https://maps.app.goo.gl/7MRGceL3K9Zidc1C7", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ESLOVENIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/SI", flagCode: "si", language: "Esloveno", currency: "Euro (EUR)", culture: "Activa y amante de la naturaleza. Mezcla de influencias alpinas, mediterráneas y balcánicas.", topImports: "Productos químicos, vehículos, maquinaria, combustibles.", countriesCrossed: 5 },
    { id: 'ESP', country: "España", capital: "Madrid", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/spain_es", customsInfo: "https://sede.agenciatributaria.gob.es/", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Relacional y conversadora. La comida y la vida social son parte del negocio.", detailsLink: "https://maps.app.goo.gl/5FCw4wUz2jTxgLfR7", fichaPaisLink: "https://www.upv.es/contenidos/ORI/info/U0891457.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/ES", flagCode: "es", language: "Español", currency: "Euro (EUR)", culture: "Regionalmente diversa, social y extrovertida. La familia y las fiestas son importantes.", topImports: "Vehículos, combustibles, maquinaria, productos farmacéuticos.", countriesCrossed: 3 },
    { id: 'EST', country: "Estonia", capital: "Tallin", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/estonia_es", customsInfo: "https://www.emta.ee/en", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Muy digital y eficiente. Comunicación directa y sin rodeos.", detailsLink: "https://maps.app.goo.gl/DEbbtj6nJuPTe8YQ7", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ESTONIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/EE", flagCode: "ee", language: "Estonio", currency: "Euro (EUR)", culture: "Reservada y tecnológica. Fuerte conexión con la naturaleza y las tradiciones nórdicas.", topImports: "Maquinaria, productos electrónicos, combustibles, vehículos.", countriesCrossed: 6 },
    { id: 'FIN', country: "Finlandia", capital: "Helsinki", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/finland_es", customsInfo: "https://tulli.fi/en/frontpage", customsStrictness: "Muy Alto (Estándares UE)", logisticalInfo: "Directa, honesta y basada en la confianza. El silencio es cómodo.", detailsLink: "https://maps.app.goo.gl/QdcdTkKUZDwpqhTD9", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/FINLANDIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/FI", flagCode: "fi", language: "Finlandés, Sueco", currency: "Euro (EUR)", culture: "Reservada, amante de la naturaleza y las saunas. Valoran la honestidad y la igualdad.", topImports: "Maquinaria, combustibles, vehículos, productos químicos.", countriesCrossed: 5 },
    { id: 'FRA', country: "Francia", capital: "París", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/france_es", customsInfo: "https://www.douane.gouv.fr/", customsStrictness: "Alto. Proteccionistas en sectores como agricultura y cultura. Normas de etiquetado estrictas.", logisticalInfo: "Formal y analítica. El idioma francés es muy valorado.", detailsLink: "https://maps.app.goo.gl/wDQxZu6chGwn8wx38", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/FRANCIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/FR", flagCode: "fr", language: "Francés", currency: "Euro (EUR)", culture: "Sofisticada y orgullosa de su herencia. La gastronomía, el arte y la moda son pilares culturales.", topImports: "Maquinaria, vehículos, productos aeroespaciales, productos farmacéuticos.", countriesCrossed: 2 },
    { id: 'GRC', country: "Grecia", capital: "Atenas", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/greece_es", customsInfo: "https://www.aade.gr/customs/teloneia/teloneiaki-ypiresia", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Relacional, flexible y hospitalaria. La confianza personal es clave.", detailsLink: "https://maps.app.goo.gl/T21vqtUBxCLsvt588", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/GRECIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/GR", flagCode: "gr", language: "Griego", currency: "Euro (EUR)", culture: "Cuna de la civilización occidental. Fuerte sentido de la familia, la hospitalidad ('filoxenia') y la tradición.", topImports: "Combustibles, productos farmacéuticos, maquinaria, vehículos.", countriesCrossed: 8 },
    { id: 'HUN', country: "Hungría", capital: "Budapest", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/hungary_es", customsInfo: "https://nav.gov.hu/", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Formal y jerárquica. La paciencia es necesaria.", detailsLink: "https://maps.app.goo.gl/1CwTsTAY2Fhw2AAE9", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/HUNGRIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/HU", flagCode: "hu", language: "Húngaro", currency: "Forinto (HUF)", culture: "Orgullosa de su historia y lengua únicas. La música y la gastronomía son importantes.", topImports: "Maquinaria, vehículos, productos electrónicos, combustibles.", countriesCrossed: 5 },
    { id: 'ITA', country: "Italia", capital: "Roma", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/italy_es", customsInfo: "https://www.adm.gov.it/portale/home", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Relacional, expresiva y flexible. El diseño y la estética son importantes.", detailsLink: "https://maps.app.goo.gl/zPVdS2XoyrANZ6ya9", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/ITALIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/IT", flagCode: "it", language: "Italiano", currency: "Euro (EUR)", culture: "Fuerte identidad regional. La familia, la moda y la comida ('la bella figura') son centrales.", topImports: "Maquinaria, vehículos, productos químicos, metales.", countriesCrossed: 5 },
    { id: 'LVA', country: "Letonia", capital: "Riga", tradeAgreement: "UE-Perú", tradeAgreementLink: "https://european-union.europa.eu/principles-countries-history/eu-countries/latvia_es", customsInfo: "https://www.vid.gov.lv/en/customs?utm_source=https%3A%2F%2Fwww.perplexity.ai%2F", customsStrictness: "Alto (Estándares UE)", logisticalInfo: "Reservada al principio, pero directa. La puntualidad es valorada.", detailsLink: "https://maps.app.goo.gl/qoXCpBat4sKK11z67", fichaPaisLink: "https://www.exteriores.gob.es/Documents/FichasPais/LETONIA_FICHA%20PAIS.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/LV", flagCode: "lv", language: "Letón", currency: "Euro (EUR)", culture: "Fuerte tradición de coros y festivales de canto. Reservados pero hospitalarios.", topImports: "Maquinaria, productos electrónicos, combustibles, vehículos.", countriesCrossed: 5 },
    { id: 'SWE', country: "Suecia", capital: "Estocolmo", tradeAgreement: "UE-Perú", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/union-europea", customsInfo: "https://www.tullverket.se/", customsStrictness: "Muy Alto. Cumplimiento estricto de normativas medioambientales y de seguridad de la UE.", logisticalInfo: "Pragmática, basada en datos. Puntualidad estricta y comunicación directa.", detailsLink: "https://es.distance.to/Países-Bajos/Stockholm,SWE", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/suecia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suecia", flagCode: "se", language: "Sueco", currency: "Corona Sueca (SEK)", culture: "Igualitaria y progresista. Se valora el consenso ('lagom') y la naturaleza.", topImports: "Vehículos, maquinaria, productos electrónicos, combustibles.", countriesCrossed: 3 },
    { id: 'CHE', country: "Suiza", capital: "Berna", tradeAgreement: "AELC", tradeAgreementLink: "https://www.efta.int/", customsInfo: "https://www.bazg.admin.ch/", customsStrictness: "Muy Alto. Precisión y calidad son claves, especialmente en relojería, farmacéuticos y alimentos.", logisticalInfo: "Formal, bien preparada y detallista. La calidad y precisión son primordiales.", detailsLink: "https://es.distance.to/Países-Bajos/Bern,CHE", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/suiza_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/suiza", flagCode: "ch", language: "Alemán, Francés, Italiano, Romanche", currency: "Franco Suizo (CHF)", culture: "Precisa, puntual y privada. Se valora la calidad, la eficiencia y el respeto por las normas.", topImports: "Productos químicos, maquinaria, vehículos, metales preciosos.", countriesCrossed: 3 },
    { id: 'TUR', country: "Turquía", capital: "Ankara", tradeAgreement: "Unión Aduanera UE", tradeAgreementLink: "https://trade.ec.europa.eu/access-to-markets/es/content/uni-n-aduanera-ue-turqu-0", customsInfo: "https://www.ticaret.gov.tr/gumruk-islemleri", customsStrictness: "Alto. Regulaciones complejas y cambiantes. Sensible en textiles y agricultura.", logisticalInfo: "Relacional y hospitalaria, pero también dura en la negociación de precios.", detailsLink: "https://es.distance.to/Países-Bajos/Ankara,TUR", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/turquia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/turquia", flagCode: "tr", language: "Turco", currency: "Lira Turca (TRY)", culture: "Puente entre Oriente y Occidente. Hospitalaria y familiar. El regateo es común en los mercados.", topImports: "Maquinaria, vehículos, combustibles, productos de acero.", countriesCrossed: 9 },
  ],
  'asia': [
    { id: 'CHN', country: 'China', capital: 'Pekín', tradeAgreement: 'TLC Perú-China', tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/china", customsInfo: 'http://english.customs.gov.cn/', customsStrictness: 'Muy Alto. Las regulaciones pueden ser complejas y cambiar rápidamente. Censura y licencias son comunes.', logisticalInfo: 'Muy formal, estructurada... Los chinos evitan la confrontación.', detailsLink: 'https://es.distance.to/Pekín,CHN/Pekín,CHN', fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/china_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/china", flagCode: "cn", language: "Chino Mandarín", currency: "Yuan (CNY)", culture: "Colectivista y jerárquica. El 'guanxi' (red de contactos) y el respeto a la autoridad son vitales.", topImports: "Productos electrónicos, maquinaria, petróleo crudo, circuitos integrados.", countriesCrossed: 1 },
    { id: 'UZB', country: "Uzbekistán", capital: "Taskent", tradeAgreement: "Sin FTA", customsInfo: "https://customs.uz/en/", customsStrictness: "Alto. Procesos burocráticos heredados de la era soviética.", logisticalInfo: "Formal, jerárquica y protocolar; se respeta mucho la autoridad.", detailsLink: "https://es.distance.to/Pekín,CHN/Taskent,UZB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uzbekistan_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uzbekistan", flagCode: "uz", language: "Uzbeko", currency: "Som Uzbeko (UZS)", culture: "Influenciada por la Ruta de la Seda. Hospitalaria y comunitaria. El respeto a los mayores es primordial.", topImports: "Maquinaria, vehículos, productos de acero, productos farmacéuticos.", countriesCrossed: 3 },
    { id: 'VNM', country: "Vietnam", capital: "Hanói", tradeAgreement: "CPTPP", tradeAgreementLink: "https://www.gob.pe/institucion/mincetur/campa%C3%B1as/328-cptpp-acuerdo-integral-y-progresista-de-asociacion-transpacifico", customsInfo: "https://www.customs.gov.vn/index.jsp?pageId=23&groupdId=2&language=en", customsStrictness: "Alto. Las regulaciones son complejas y la interpretación puede variar.", logisticalInfo: "Formal pero basada en relaciones personales; evitan decir “no” directamente.", detailsLink: "https://es.distance.to/Pekín,CHN/Hanoi,VNM", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/vietnam_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/vietnam", flagCode: "vn", language: "Vietnamita", currency: "Dong (VND)", culture: "Respetuosa de la jerarquía y la edad. La cara ('mặt') y el colectivismo son conceptos clave.", topImports: "Productos electrónicos, maquinaria, textiles, plásticos.", countriesCrossed: 2 },
    { id: 'IND', country: "India", capital: "Nueva Delhi", tradeAgreement: "En negociación", customsInfo: "https://www.cbic.gov.in/", customsStrictness: "Muy Alto. Conocida por su burocracia ('Red Tape') y regulaciones complejas.", logisticalInfo: "Jerárquica y relacional. La negociación puede ser larga y detallada.", detailsLink: "https://es.distance.to/Pekín,CHN/New-Delhi,IND", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/india_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/india", flagCode: "in", language: "Hindi, Inglés", currency: "Rupia India (INR)", culture: "Extremadamente diversa en religión, idioma y etnia. La familia y la jerarquía son muy importantes.", topImports: "Petróleo crudo, oro, productos electrónicos, maquinaria.", countriesCrossed: 2 },
  ],
  'africa': [
    { id: 'DZA', country: "Argelia", capital: "Argel", tradeAgreement: "AfCFTA", tradeAgreementLink: "https://au-afcfta.org/", customsInfo: "https://douane.gov.dz/?lang=fr", customsStrictness: "Alto. Burocracia significativa y requisitos de documentación en francés.", logisticalInfo: "Negociación formal y jerárquica, orientada a resultados.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Algiers,DZA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/argelia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/argelia", flagCode: "dz", language: "Árabe, Bereber", currency: "Dinar Argelino (DZD)", culture: "Conservadora y patriarcal. La religión (Islam) y la familia son los pilares de la sociedad.", topImports: "Cereales, maquinaria, vehículos, productos farmacéuticos.", countriesCrossed: 10 },
    { id: 'TUN', country: "Túnez", capital: "Túnez", tradeAgreement: "AfCFTA", tradeAgreementLink: "https://au-afcfta.org/", customsInfo: "http://www.douane.gov.tn/", customsStrictness: "Medio-Alto. Proceso de modernización en curso. Sectores como el textil son sensibles.", logisticalInfo: "Se valora la cortesía y la construcción de relaciones.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Tunis,TUN", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/tunez_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/tunez", flagCode: "tn", language: "Árabe", currency: "Dinar Tunecino (TND)", culture: "Considerada una de las más liberales del mundo árabe. Hospitalaria y orientada a la familia.", topImports: "Textiles, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 11 },
    { id: 'UGA', country: "Uganda", capital: "Kampala", tradeAgreement: "AfCFTA", tradeAgreementLink: "https://au-afcfta.org/", customsInfo: "https://ura.go.ug/en/", customsStrictness: "Medio. La corrupción puede ser un desafío. Documentación clara es vital.", logisticalInfo: "Negociación abierta, se valora la honestidad.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Kampala,UGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/uganda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/uganda", flagCode: "ug", language: "Inglés, Suajili", currency: "Chelín Ugandés (UGX)", culture: "Étnicamente diversa. La comunidad y la familia extendida son muy importantes.", topImports: "Petróleo, vehículos, productos farmacéuticos, maquinaria.", countriesCrossed: 5 },
    { id: 'ZMB', country: "Zambia", capital: "Lusaka", tradeAgreement: "SADC; AfCFTA", tradeAgreementLink: "https://www.sadc.int/", customsInfo: "https://www.zra.org.zm/", customsStrictness: "Medio. Regulaciones mineras y agrícolas son particularly importantes.", logisticalInfo: "Negociación formal, basada en acuerdos firmes.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Lusaka,ZMB", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/zambia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/zambia", flagCode: "zm", language: "Inglés", currency: "Kwacha Zambiano (ZMW)", culture: "Pacífica y amigable. El respeto a los mayores es un valor fundamental.", topImports: "Maquinaria, combustibles, fertilizantes, productos químicos.", countriesCrossed: 3 },
    { id: 'SLE', country: "Sierra Leona", capital: "Freetown", tradeAgreement: "AfCFTA", tradeAgreementLink: "https://au-afcfta.org/", customsInfo: "https://www.nra.gov.sl/", customsStrictness: "Bajo-Medio. Desafíos logísticos y de infraestructura pueden ser más problemáticos que las regulaciones.", logisticalInfo: "Negociación relacional, se prioriza la confianza.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Freetown,SLE", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/sierraleona_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/sierra-leona", flagCode: "sl", language: "Inglés", currency: "Leone (SLL)", culture: "Fuerte sentido de comunidad. La religión y las sociedades secretas juegan un papel importante.", topImports: "Arroz, maquinaria, vehículos, combustibles.", countriesCrossed: 10 },
    { id: 'NGA', country: "Nigeria", capital: "Abuya", tradeAgreement: "AfCFTA", tradeAgreementLink: "https://au-afcfta.org/", customsInfo: "https://customs.gov.ng/", customsStrictness: "Alto. Regulaciones complejas y riesgo de corrupción. El sector petrolero tiene sus propias reglas.", logisticalInfo: "Enfocada en el precio y las relaciones personales. Puede ser una negociación dura.", detailsLink: "https://es.distance.to/Johannesburgo,ZAF/Abuja,NGA", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nigeria_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nigeria", flagCode: "ng", language: "Inglés", currency: "Naira (NGN)", culture: "Muy diversa étnicamente. Emprendedora y extrovertida. El respeto a la edad y la jerarquía es clave.", topImports: "Combustibles, maquinaria, vehículos, cereales.", countriesCrossed: 7 },
  ],
  'oceania': [
    { id: 'AUS_syd', country: "Australia", capital: "Sídney", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto. Bioseguridad es extremadamente estricta (agricultura, alimentos).", logisticalInfo: "Práctica y enfocada en resultados; valoran la rapidez.", detailsLink: "https://es.distance.to/Sídney/Sídney", fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/australia_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_mel', country: "Australia", capital: "Melbourne", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto. Bioseguridad es extremadamente estricta (agricultura, alimentos).", logisticalInfo: "Formal, estructurada; muy estricta puntualidad.", detailsLink: "https://es.distance.to/Sídney/Melbourne", fichaPaisLink: "https://www.unsaltoaaustralia.com/melbourne/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_bri', country: "Australia", capital: "Brisbane", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto (Bioseguridad).", logisticalInfo: "Relajada y enfocada en el estilo de vida al aire libre.", detailsLink: "https://es.distance.to/Sídney/Brisbane", fichaPaisLink: "https://www.unsaltoaaustralia.com/brisbane/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_can', country: "Australia", capital: "Canberra", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto (Bioseguridad).", logisticalInfo: "Más formal por ser la capital política.", detailsLink: "https://es.distance.to/Sídney/Canberra", fichaPaisLink: "https://www.unsaltoaaustralia.com/canberra/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_ade', country: "Australia", capital: "Adelaide", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto (Bioseguridad).", logisticalInfo: "Famosa por su industria vinícola y festivales.", detailsLink: "https://es.distance.to/Sídney/Adelaide", fichaPaisLink: "https://www.unsaltoaaustralia.com/adelaide/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_per', country: "Australia", capital: "Perth", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto (Bioseguridad).", logisticalInfo: "Centro de la industria minera y de recursos.", detailsLink: "https://es.distance.to/Sídney/Perth", fichaPaisLink: "https://www.unsaltoaaustralia.com/perth/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
    { id: 'AUS_dar', country: "Australia", capital: "Darwin", tradeAgreement: "TLC Perú-Australia", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/australia", customsInfo: "https://www.abf.gov.au/", customsStrictness: "Muy Alto (Bioseguridad).", logisticalInfo: "Clima tropical y puerta de entrada a Asia.", detailsLink: "https://es.distance.to/Sídney/Darwin", fichaPaisLink: "https://www.unsaltoaaustralia.com/darwin/", indicadoresLink: "https://datos.bancomundial.org/pais/australia", flagCode: "au", language: "Inglés", currency: "Dólar Australiano (AUD)", culture: "Relajada, informal y directa. Se valora el igualitarismo y el humor autocrítico.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1 },
  ],
  'otros': [
    ...["Londres", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Oxford", "Cambridge", "Sheffield", "Newcastle upon Tyne", "Nottingham", "Southampton", "Brighton", "Bath", "Cardiff", "Milton Keynes", "York", "Sunderland"].map(city => ({ id: `gbr-${city.toLowerCase().replace(/ /g, '-')}`, country: "Gran Bretaña", capital: city, tradeAgreement: "TLC Perú-Reino Unido", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/reino-unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", customsStrictness: "Alto", logisticalInfo: "Profesional y puntual.", detailsLink: `https://es.distance.to/Londres/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "gb", language: "Inglés", currency: "Libra Esterlina (GBP)", culture: "Reservada y educada.", topImports: "Vehículos, maquinaria, combustibles, productos farmacéuticos.", countriesCrossed: 1 })),
    ...["Edimburgo", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth", "Elgin"].map(city => ({ id: `sct-${city.toLowerCase().replace(/ /g, '-')}`, country: "Escocia", capital: city, tradeAgreement: "TLC Perú-Reino Unido", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/reino-unido", customsInfo: "https://www.gov.uk/government/organisations/hm-revenue-customs", customsStrictness: "Alto", logisticalInfo: "Pragmáticos y directos.", detailsLink: `https://es.distance.to/Edimburgo/${city.replace(/ /g, '-')}`, fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/reinounido_ficha%20pais.pdf", fichaPaisTooltip: "Escocia es una nación constitutiva del Reino Unido, ubicada al noroeste de Europa en la isla de Gran Bretaña", indicadoresLink: "#", flagCode: "gb-sct", language: "Inglés, Gaélico", currency: "Libra Esterlina (GBP)", culture: "Fuerte identidad cultural.", topImports: "Maquinaria, productos electrónicos, whisky, pescado.", countriesCrossed: 1 })),
    ...["Vittoriosa", "Cospicua", "Senglea"].map(city => ({ id: `mlt-${city.toLowerCase()}`, country: "Malta", capital: city, tradeAgreement: "UE-Perú", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/union-europea", customsInfo: "https://customs.gov.mt/", customsStrictness: "Medio", logisticalInfo: "Relacional y flexible.", detailsLink: `https://es.distance.to/Valeta/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "mt", language: "Maltés, Inglés", currency: "Euro (EUR)", culture: "Influencia mediterránea y británica.", topImports: "Combustibles, maquinaria, yates, productos farmacéuticos.", countriesCrossed: 1 })),
    ...["Dublín", "Cork", "Galway", "Límerick", "Dundalk", "Waterford", "Drogheda", "Navan", "Bray"].map(city => ({ id: `irl-${city.toLowerCase()}`, country: "Irlanda", capital: city, tradeAgreement: "UE-Perú", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/union-europea", customsInfo: "https://www.revenue.ie/en/customs-traders-and-agents/index.aspx", customsStrictness: "Alto (normas UE)", logisticalInfo: "Amigable y directa.", detailsLink: `https://es.distance.to/Dublin/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "ie", language: "Irlandés, Inglés", currency: "Euro (EUR)", culture: "Acogedora y social.", topImports: "Productos farmacéuticos, maquinaria, productos químicos, aeronaves.", countriesCrossed: 1 })),
    ...["Tokio", "Osaka", "Kyoto", "Fukuoka", "Kobe", "Nagoya", "Hiroshima", "Sendai", "Nagasaki", "Chiba", "Kumamoto", "Saitama", "Shizuoka", "Nagano", "Yokohama", "Nara", "Utsunomiya", "Kanagawa", "Kanazawa", "Hakone", "Nikkō", "Matsuyama", "Okayama"].map(city => ({ id: `jpn-${city.toLowerCase()}`, country: "Japon", capital: city, tradeAgreement: "CPTPP", tradeAgreementLink: "https://www.gob.pe/institucion/mincetur/campa%C3%B1as/328-cptpp-acuerdo-integral-y-progresista-de-asociacion-transpacifico", customsInfo: "https://www.customs.go.jp/english/", customsStrictness: "Muy alto", logisticalInfo: "Extremadamente formal y puntual.", detailsLink: `https://es.distance.to/Tokio/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "jp", language: "Japonés", currency: "Yen (JPY)", culture: "Respeto por la jerarquía y la etiqueta.", topImports: "Combustibles, productos electrónicos, maquinaria, productos farmacéuticos.", countriesCrossed: 1 })),
    ...["Seúl", "Busan", "Daegu", "Incheon", "Daejeon", "Ulsan", "Gwangjung", "Pyeongtaek"].map(city => ({ id: `kor-${city.toLowerCase()}`, country: "Corea del Sur", capital: city, tradeAgreement: "TLC Perú-Corea", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/corea", customsInfo: "https://www.customs.go.kr/eng/main.do", customsStrictness: "Alto", logisticalInfo: "Rápida y relacional.", detailsLink: `https://es.distance.to/Seul/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "kr", language: "Coreano", currency: "Won (KRW)", culture: "Dinámica y tecnológica.", topImports: "Petróleo crudo, circuitos integrados, maquinaria, gas natural.", countriesCrossed: 1 })),
    ...[
      { city: 'Auckland', km: 643, link: 'https://www.calcularruta.com/wellington-auckland.html' },
      { city: 'Hamilton', km: 516, link: 'https://www.calcularruta.com/wellington-hamilton.html' },
      { city: 'Tauranga', km: 514, link: 'https://www.calcularruta.com/wellington-tauranga.html' },
      { city: 'Napier', km: 316, link: 'https://www.calcularruta.com/wellington-napier.html' },
      { city: 'Palmerston North', km: 141, link: 'https://www.calcularruta.com/wellington-palmerston-north.html#google_vignette' },
      { city: 'Rotorua', km: 452, link: 'https://www.calcularruta.com/wellington-rotorua.html' },
      { city: 'Whanganui', km: 194, link: 'https://www.calcularruta.com/wellington-whanganui.html' },
      { city: 'Gisborne', km: 527, link: 'https://www.calcularruta.com/wellington-gisborne.html' },
      { city: 'Taupō', km: 371, link: 'https://www.calcularruta.com/wellington-taupo.html' },
      { city: 'Whangārei', km: 794, link: 'https://www.calcularruta.com/wellington-whangarei.html#google_vignette' }
    ].map(item => ({ id: `nzn-${item.city.toLowerCase().replace('ā', 'a')}`, country: "Nueva Zelanda (Isla Norte)", capital: item.city, tradeAgreement: "CPTPP", tradeAgreementLink: "https://www.gob.pe/institucion/mincetur/campa%C3%B1as/328-cptpp-acuerdo-integral-y-progresista-de-asociacion-transpacifico", customsInfo: "https://www.customs.govt.nz/", customsStrictness: "Muy Alto (Bioseguridad)", logisticalInfo: "Directa y pragmática.", detailsLink: item.link, fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nuevazelanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nueva-zelandia", flagCode: "nz", language: "Inglés, Maorí", currency: "Dólar Neozelandés (NZD)", culture: "Relajada y amante de la naturaleza.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1, kilometers: item.km })),
    ...[
      { city: 'Picton', km: 336, link: 'https://www.calcularruta.com/christchurch-picton.html' },
      { city: 'Kaikoura', km: 182, link: 'https://www.calcularruta.com/de-christchurch-a-kaikoura.html' },
      { city: 'Blenheim', km: 310, link: 'https://www.calcularruta.com/de-christchurch-a-blenheim.html' },
      { city: 'Greymouth', km: 244, link: 'https://www.calcularruta.com/de-christchurch-a-greymouth.html' },
      { city: 'Queenstown', km: 481, link: 'https://www.calcularruta.com/christchurch-queenstown.html' },
      { city: 'Timaru', km: 163, link: 'https://www.calcularruta.com/christchurch-timaru.html' },
      { city: 'Dunedin', km: 361, link: 'https://www.calcularruta.com/christchurch-dunedin.html' },
      { city: 'Invercargill', km: 565, link: 'https://www.calcularruta.com/christchurch-invercargill.html' }
    ].map(item => ({ id: `nzs-${item.city.toLowerCase()}`, country: "Nueva Zelanda (Isla Sur)", capital: item.city, tradeAgreement: "CPTPP", tradeAgreementLink: "https://www.gob.pe/institucion/mincetur/campa%C3%B1as/328-cptpp-acuerdo-integral-y-progresista-de-asociacion-transpacifico", customsInfo: "https://www.customs.govt.nz/", customsStrictness: "Muy Alto (Bioseguridad)", logisticalInfo: "Directa y pragmática.", detailsLink: item.link, fichaPaisLink: "https://www.exteriores.gob.es/documents/fichaspais/nuevazelanda_ficha%20pais.pdf", indicadoresLink: "https://datos.bancomundial.org/pais/nueva-zelandia", flagCode: "nz", language: "Inglés, Maorí", currency: "Dólar Neozelandés (NZD)", culture: "Aventura y paisajes espectaculares.", topImports: "Vehículos, maquinaria, combustibles, productos electrónicos.", countriesCrossed: 1, kilometers: item.km })),
    ...["Manama", "Al Muharraq", "Riffa", "Madinat Hamad", "Madinat 'Isa", "Sitra", "Jidhafs"].map(city => ({ id: `bhr-${city.toLowerCase().replace(/ /g, '-').replace(/'/g, '')}`, country: "Bahréin", capital: city, tradeAgreement: "No específico", customsInfo: "https://www.bahraincustoms.gov.bh/", customsStrictness: "Medio", logisticalInfo: "Relacional y de negocios.", detailsLink: `https://es.distance.to/Manama/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "bh", language: "Árabe", currency: "Dinar Bahreiní (BHD)", culture: "Centro financiero y comercial.", topImports: "Vehículos, maquinaria, oro, productos de aluminio.", countriesCrossed: 1 })),
    ...["Nicosia", "Limasol", "Larnaca", "Pafos", "Famagusta", "Kyrenia", "Ayia Napa", "Paralimni"].map(city => ({ id: `cyp-${city.toLowerCase().replace(/ /g, '-')}`, country: "Chipre", capital: city, tradeAgreement: "UE-Perú", tradeAgreementLink: "http://www.acuerdoscomerciales.gob.pe/index.php/es/acuerdos-comerciales/union-europea", customsInfo: "https://www.mof.gov.cy/mof/customs/customs.nsf/index_en/index_en", customsStrictness: "Alto (normas UE)", logisticalInfo: "Flexible y orientado a relaciones.", detailsLink: `https://es.distance.to/Nicosia/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "cy", language: "Griego, Turco", currency: "Euro (EUR)", culture: "Cruce de culturas europea y de Oriente Medio.", topImports: "Combustibles, vehículos, maquinaria, productos farmacéuticos.", countriesCrossed: 1 })),
    ...["Yakarta", "Bandung", "Bekasi", "Bogor", "Depok", "Malang", "Semarang", "Surabaya", "Yogyakarta", "Cirebon", "Sukabumi", "Tasikmalaya"].map(city => ({ id: `idn-${city.toLowerCase()}`, country: "Indonesia", capital: city, tradeAgreement: "En negociación", customsInfo: "https://www.beacukai.go.id/", customsStrictness: "Alto", logisticalInfo: "Indirecta y relacional.", detailsLink: `https://es.distance.to/Yakarta/${city}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "id", language: "Indonesio", currency: "Rupia Indonesia (IDR)", culture: "Extremadamente diversa.", topImports: "Maquinaria, combustibles, productos químicos, productos de acero.", countriesCrossed: 1 })),
    ...["Johannesburgo", "Ciudad del Cabo", "Durban", "Pretoria", "Puerto Elizabeth"].map(city => ({ id: `zaf-${city.toLowerCase().replace(/ /g, '-')}`, country: "Sudáfrica", capital: city, tradeAgreement: "SADC; AfCFTA", tradeAgreementLink: "https://www.sadc.int/", customsInfo: "https://www.sars.gov.za/", customsStrictness: "Alto", logisticalInfo: "Directa y pragmática, pero las relaciones son importantes.", detailsLink: `https://es.distance.to/Johannesburgo/${city.replace(/ /g, '-')}`, fichaPaisLink: "#", indicadoresLink: "#", flagCode: "za", language: "11 idiomas oficiales", currency: "Rand (ZAR)", culture: "La 'Nación del Arcoíris', muy diversa.", topImports: "Maquinaria, combustibles, vehículos, productos electrónicos.", countriesCrossed: 1 })),
  ],
};

    

